/*
 * InternetData API
 * The InternetData API. Please see https://docs.internetdata.io/api for more details. 
 *
 * The version of the OpenAPI document: 2026.09.05
 * Contact: dev@internetdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.internetdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.internetdata.internal.ApiClient;
/**
 * DatabaseChecksums
 */
@JsonPropertyOrder({
  DatabaseChecksums.JSON_PROPERTY_MD5,
  DatabaseChecksums.JSON_PROPERTY_SHA1,
  DatabaseChecksums.JSON_PROPERTY_SHA256,
  DatabaseChecksums.JSON_PROPERTY_SHA512
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseChecksums {
  public static final String JSON_PROPERTY_MD5 = "md5";
  @javax.annotation.Nonnull
  private String md5;

  public static final String JSON_PROPERTY_SHA1 = "sha1";
  @javax.annotation.Nonnull
  private String sha1;

  public static final String JSON_PROPERTY_SHA256 = "sha256";
  @javax.annotation.Nonnull
  private String sha256;

  public static final String JSON_PROPERTY_SHA512 = "sha512";
  @javax.annotation.Nonnull
  private String sha512;

  public DatabaseChecksums() { 
  }

  public DatabaseChecksums md5(@javax.annotation.Nonnull String md5) {
    this.md5 = md5;
    return this;
  }

  /**
   * Hex-encoded MD5 digest.
   * @return md5
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MD5, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMd5() {
    return md5;
  }


  @JsonProperty(value = JSON_PROPERTY_MD5, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMd5(@javax.annotation.Nonnull String md5) {
    this.md5 = md5;
  }


  public DatabaseChecksums sha1(@javax.annotation.Nonnull String sha1) {
    this.sha1 = sha1;
    return this;
  }

  /**
   * Hex-encoded SHA-1 digest.
   * @return sha1
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SHA1, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSha1() {
    return sha1;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA1, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSha1(@javax.annotation.Nonnull String sha1) {
    this.sha1 = sha1;
  }


  public DatabaseChecksums sha256(@javax.annotation.Nonnull String sha256) {
    this.sha256 = sha256;
    return this;
  }

  /**
   * Hex-encoded SHA-256 digest.
   * @return sha256
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SHA256, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSha256() {
    return sha256;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA256, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSha256(@javax.annotation.Nonnull String sha256) {
    this.sha256 = sha256;
  }


  public DatabaseChecksums sha512(@javax.annotation.Nonnull String sha512) {
    this.sha512 = sha512;
    return this;
  }

  /**
   * Hex-encoded SHA-512 digest.
   * @return sha512
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SHA512, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSha512() {
    return sha512;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA512, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSha512(@javax.annotation.Nonnull String sha512) {
    this.sha512 = sha512;
  }


  /**
   * Return true if this DbChecksums object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseChecksums dbChecksums = (DatabaseChecksums) o;
    return Objects.equals(this.md5, dbChecksums.md5) &&
        Objects.equals(this.sha1, dbChecksums.sha1) &&
        Objects.equals(this.sha256, dbChecksums.sha256) &&
        Objects.equals(this.sha512, dbChecksums.sha512);
  }

  @Override
  public int hashCode() {
    return Objects.hash(md5, sha1, sha256, sha512);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseChecksums {\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sha1: ").append(toIndentedString(sha1)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("    sha512: ").append(toIndentedString(sha512)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `md5` to the URL query string
    if (getMd5() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smd5%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMd5()))));
    }

    // add `sha1` to the URL query string
    if (getSha1() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha1%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha1()))));
    }

    // add `sha256` to the URL query string
    if (getSha256() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha256%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha256()))));
    }

    // add `sha512` to the URL query string
    if (getSha512() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssha512%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSha512()))));
    }

    return joiner.toString();
  }
}

