/*
 * InternetData API
 * The InternetData API. Please see https://docs.internetdata.io/api for more details. 
 *
 * The version of the OpenAPI document: 2026.09.05
 * Contact: dev@internetdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.internetdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.internetdata.internal.ApiClient;
/**
 * DatabaseVersion
 */
@JsonPropertyOrder({
  DatabaseVersion.JSON_PROPERTY_ID,
  DatabaseVersion.JSON_PROPERTY_VERSION,
  DatabaseVersion.JSON_PROPERTY_SUMMARY,
  DatabaseVersion.JSON_PROPERTY_FORMATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseVersion {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull
  private Integer version;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  /**
   * Gets or Sets formats
   */
  public enum FormatsEnum {
    CSVGZ(String.valueOf("csvgz")),
    
    MMDB(String.valueOf("mmdb"));

    private String value;

    FormatsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatsEnum fromValue(String value) {
      for (FormatsEnum b : FormatsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMATS = "formats";
  @javax.annotation.Nonnull
  private List<FormatsEnum> formats = new ArrayList<>();

  public DatabaseVersion() { 
  }

  public DatabaseVersion id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The versioned id. Pass this to &#x60;download&#x60;, &#x60;checksum&#x60; and &#x60;metadata&#x60;.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public DatabaseVersion version(@javax.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public DatabaseVersion summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public DatabaseVersion formats(@javax.annotation.Nonnull List<FormatsEnum> formats) {
    this.formats = formats;
    return this;
  }

  public DatabaseVersion addFormatsItem(FormatsEnum formatsItem) {
    if (this.formats == null) {
      this.formats = new ArrayList<>();
    }
    this.formats.add(formatsItem);
    return this;
  }

  /**
   * The formats this version is BUILT in. Asking for another is a 400, not a gap - the &#x60;_provider&#x60; catalogs are keyed by provider id, so no MMDB exists for them. 
   * @return formats
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<FormatsEnum> getFormats() {
    return formats;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMATS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormats(@javax.annotation.Nonnull List<FormatsEnum> formats) {
    this.formats = formats;
  }


  /**
   * Return true if this DatabaseVersion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseVersion databaseVersion = (DatabaseVersion) o;
    return Objects.equals(this.id, databaseVersion.id) &&
        Objects.equals(this.version, databaseVersion.version) &&
        Objects.equals(this.summary, databaseVersion.summary) &&
        Objects.equals(this.formats, databaseVersion.formats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, summary, formats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseVersion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    formats: ").append(toIndentedString(formats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `formats` to the URL query string
    if (getFormats() != null) {
      for (int i = 0; i < getFormats().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sformats%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getFormats().get(i)))));
      }
    }

    return joiner.toString();
  }
}

