/*
 * InternetData API
 * The InternetData API. Please see https://docs.internetdata.io/api for more details. 
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: dev@internetdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.internetdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.internetdata.model.DatabaseVersion;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.internetdata.internal.ApiClient;
/**
 * One database FAMILY, with your organization&#39;s licence beside it. A licence covers the family, while a download names a specific version, so the ids passed to &#x60;download&#x60; and &#x60;checksum&#x60; come from &#x60;versions&#x60;. 
 */
@JsonPropertyOrder({
  Database.JSON_PROPERTY_BASE,
  Database.JSON_PROPERTY_NAME,
  Database.JSON_PROPERTY_SUMMARY,
  Database.JSON_PROPERTY_STANDING,
  Database.JSON_PROPERTY_REDISTRIBUTION,
  Database.JSON_PROPERTY_STARTS,
  Database.JSON_PROPERTY_EXPIRES,
  Database.JSON_PROPERTY_VERSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Database {
  public static final String JSON_PROPERTY_BASE = "base";
  @javax.annotation.Nonnull
  private String base;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nonnull
  private String summary;

  /**
   * &#x60;licensed&#x60; is a live grant, &#x60;expired&#x60; one whose term has ended, and &#x60;unlicensed&#x60; a database published but never bought. 
   */
  public enum StandingEnum {
    LICENSED(String.valueOf("licensed")),
    
    EXPIRED(String.valueOf("expired")),
    
    UNLICENSED(String.valueOf("unlicensed"));

    private String value;

    StandingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StandingEnum fromValue(String value) {
      for (StandingEnum b : StandingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STANDING = "standing";
  @javax.annotation.Nonnull
  private StandingEnum standing;

  /**
   * What your licence permits you to do with the data. Null when there is no licence. 
   */
  public enum RedistributionEnum {
    EVALUATION(String.valueOf("evaluation")),
    
    INTERNAL(String.valueOf("internal")),
    
    REDISTRIBUTE(String.valueOf("redistribute"));

    private String value;

    RedistributionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RedistributionEnum fromValue(String value) {
      for (RedistributionEnum b : RedistributionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_REDISTRIBUTION = "redistribution";
  @javax.annotation.Nullable
  private RedistributionEnum redistribution;

  public static final String JSON_PROPERTY_STARTS = "starts";
  @javax.annotation.Nullable
  private OffsetDateTime starts;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @javax.annotation.Nullable
  private OffsetDateTime expires;

  public static final String JSON_PROPERTY_VERSIONS = "versions";
  @javax.annotation.Nonnull
  private List<DatabaseVersion> versions = new ArrayList<>();

  public Database() { 
  }

  public Database base(@javax.annotation.Nonnull String base) {
    this.base = base;
    return this;
  }

  /**
   * The family, e.g. &#x60;vpn_ip&#x60;. What a licence is held against.
   * @return base
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BASE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBase() {
    return base;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBase(@javax.annotation.Nonnull String base) {
    this.base = base;
  }


  public Database name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Database summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * One line on what the newest version contains.
   * @return summary
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public Database standing(@javax.annotation.Nonnull StandingEnum standing) {
    this.standing = standing;
    return this;
  }

  /**
   * &#x60;licensed&#x60; is a live grant, &#x60;expired&#x60; one whose term has ended, and &#x60;unlicensed&#x60; a database published but never bought. 
   * @return standing
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STANDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StandingEnum getStanding() {
    return standing;
  }


  @JsonProperty(value = JSON_PROPERTY_STANDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStanding(@javax.annotation.Nonnull StandingEnum standing) {
    this.standing = standing;
  }


  public Database redistribution(@javax.annotation.Nullable RedistributionEnum redistribution) {
    this.redistribution = redistribution;
    return this;
  }

  /**
   * What your licence permits you to do with the data. Null when there is no licence. 
   * @return redistribution
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REDISTRIBUTION, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RedistributionEnum getRedistribution() {
    return redistribution;
  }


  @JsonProperty(value = JSON_PROPERTY_REDISTRIBUTION, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRedistribution(@javax.annotation.Nullable RedistributionEnum redistribution) {
    this.redistribution = redistribution;
  }


  public Database starts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
    return this;
  }

  /**
   * Get starts
   * @return starts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getStarts() {
    return starts;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStarts(@javax.annotation.Nullable OffsetDateTime starts) {
    this.starts = starts;
  }


  public Database expires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * Null when the licence has no end date, or when there is none.
   * @return expires
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getExpires() {
    return expires;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
  }


  public Database versions(@javax.annotation.Nonnull List<DatabaseVersion> versions) {
    this.versions = versions;
    return this;
  }

  public Database addVersionsItem(DatabaseVersion versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

  /**
   * Every published version of this family, oldest first. Old versions are frozen rather than migrated, so both stay downloadable. 
   * @return versions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DatabaseVersion> getVersions() {
    return versions;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersions(@javax.annotation.Nonnull List<DatabaseVersion> versions) {
    this.versions = versions;
  }


  /**
   * Return true if this Database object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Database database = (Database) o;
    return Objects.equals(this.base, database.base) &&
        Objects.equals(this.name, database.name) &&
        Objects.equals(this.summary, database.summary) &&
        Objects.equals(this.standing, database.standing) &&
        Objects.equals(this.redistribution, database.redistribution) &&
        Objects.equals(this.starts, database.starts) &&
        Objects.equals(this.expires, database.expires) &&
        Objects.equals(this.versions, database.versions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, name, summary, standing, redistribution, starts, expires, versions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Database {\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    standing: ").append(toIndentedString(standing)).append("\n");
    sb.append("    redistribution: ").append(toIndentedString(redistribution)).append("\n");
    sb.append("    starts: ").append(toIndentedString(starts)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `base` to the URL query string
    if (getBase() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbase%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBase()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSummary()))));
    }

    // add `standing` to the URL query string
    if (getStanding() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstanding%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStanding()))));
    }

    // add `redistribution` to the URL query string
    if (getRedistribution() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sredistribution%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedistribution()))));
    }

    // add `starts` to the URL query string
    if (getStarts() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstarts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStarts()))));
    }

    // add `expires` to the URL query string
    if (getExpires() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpires%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpires()))));
    }

    // add `versions` to the URL query string
    if (getVersions() != null) {
      for (int i = 0; i < getVersions().size(); i++) {
        if (getVersions().get(i) != null) {
          joiner.add(getVersions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sversions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

