/*
 * InternetData API
 * The InternetData API. Please see https://docs.internetdata.io/api for more details. 
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: dev@internetdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.internetdata.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.internetdata.model.DatabaseChecksums;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.internetdata.internal.ApiClient;
/**
 * DatabaseChecksumsResponse
 */
@JsonPropertyOrder({
  DatabaseChecksumsResponse.JSON_PROPERTY_ID,
  DatabaseChecksumsResponse.JSON_PROPERTY_FORMAT,
  DatabaseChecksumsResponse.JSON_PROPERTY_CHECKSUMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseChecksumsResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  /**
   * Gets or Sets format
   */
  public enum FormatEnum {
    CSVGZ(String.valueOf("csvgz")),
    
    MMDB(String.valueOf("mmdb"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nonnull
  private FormatEnum format;

  public static final String JSON_PROPERTY_CHECKSUMS = "checksums";
  @javax.annotation.Nonnull
  private DatabaseChecksums checksums;

  public DatabaseChecksumsResponse() { 
  }

  public DatabaseChecksumsResponse id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public DatabaseChecksumsResponse format(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@javax.annotation.Nonnull FormatEnum format) {
    this.format = format;
  }


  public DatabaseChecksumsResponse checksums(@javax.annotation.Nonnull DatabaseChecksums checksums) {
    this.checksums = checksums;
    return this;
  }

  /**
   * Get checksums
   * @return checksums
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHECKSUMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DatabaseChecksums getChecksums() {
    return checksums;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECKSUMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChecksums(@javax.annotation.Nonnull DatabaseChecksums checksums) {
    this.checksums = checksums;
  }


  /**
   * Return true if this DatabaseChecksumsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseChecksumsResponse databaseChecksumsResponse = (DatabaseChecksumsResponse) o;
    return Objects.equals(this.id, databaseChecksumsResponse.id) &&
        Objects.equals(this.format, databaseChecksumsResponse.format) &&
        Objects.equals(this.checksums, databaseChecksumsResponse.checksums);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, format, checksums);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseChecksumsResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    checksums: ").append(toIndentedString(checksums)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sformat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFormat()))));
    }

    // add `checksums` to the URL query string
    if (getChecksums() != null) {
      joiner.add(getChecksums().toUrlQueryString(prefix + "checksums" + suffix));
    }

    return joiner.toString();
  }
}

