/*
 * InternetData API
 * The InternetData API. Please see https://docs.internetdata.io/api for more details. 
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: dev@internetdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.internetdata.api;

import io.internetdata.internal.ApiClient;
import io.internetdata.internal.ApiException;
import io.internetdata.internal.ApiResponse;
import io.internetdata.internal.Configuration;
import io.internetdata.internal.Pair;

import io.internetdata.model.DatabaseChecksumsResponse;
import io.internetdata.model.DatabaseList;
import io.internetdata.model.DatabaseMetadata;
import io.internetdata.model.DownloadList;
import io.internetdata.model.ErrorBody;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DatabaseV2Api {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public DatabaseV2Api() {
    this(Configuration.getDefaultApiClient());
  }

  public DatabaseV2Api(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @return DatabaseChecksumsResponse
   * @throws ApiException if fails to make API call
   */
  public DatabaseChecksumsResponse databaseChecksumV2(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return databaseChecksumV2(id, format, null);
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @param headers Optional headers to include in the request
   * @return DatabaseChecksumsResponse
   * @throws ApiException if fails to make API call
   */
  public DatabaseChecksumsResponse databaseChecksumV2(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    ApiResponse<DatabaseChecksumsResponse> localVarResponse = databaseChecksumV2WithHttpInfo(id, format, headers);
    return localVarResponse.getData();
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @return ApiResponse&lt;DatabaseChecksumsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseChecksumsResponse> databaseChecksumV2WithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return databaseChecksumV2WithHttpInfo(id, format, null);
  }

  /**
   * Checksums for one published file, to verify a download
   * 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DatabaseChecksumsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseChecksumsResponse> databaseChecksumV2WithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = databaseChecksumV2RequestBuilder(id, format, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("databaseChecksumV2", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DatabaseChecksumsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DatabaseChecksumsResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DatabaseChecksumsResponse>() {});
        

        return new ApiResponse<DatabaseChecksumsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder databaseChecksumV2RequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling databaseChecksumV2");
    }
    // verify the required parameter 'format' is set
    if (format == null) {
      throw new ApiException(400, "Missing the required parameter 'format' when calling databaseChecksumV2");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/database/checksum";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * What is inside one database - schema, sample rows, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the database is built in. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @return DatabaseMetadata
   * @throws ApiException if fails to make API call
   */
  public DatabaseMetadata databaseMetadataV2(@javax.annotation.Nonnull String id) throws ApiException {
    return databaseMetadataV2(id, null);
  }

  /**
   * What is inside one database - schema, sample rows, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the database is built in. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param headers Optional headers to include in the request
   * @return DatabaseMetadata
   * @throws ApiException if fails to make API call
   */
  public DatabaseMetadata databaseMetadataV2(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<DatabaseMetadata> localVarResponse = databaseMetadataV2WithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * What is inside one database - schema, sample rows, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the database is built in. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @return ApiResponse&lt;DatabaseMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseMetadata> databaseMetadataV2WithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return databaseMetadataV2WithHttpInfo(id, null);
  }

  /**
   * What is inside one database - schema, sample rows, row count, sizes
   * Poll this to decide whether today&#39;s build is worth fetching: it carries &#x60;updated&#x60; and &#x60;entries&#x60; without downloading anything.  No &#x60;format&#x60; parameter - one document describes every format the database is built in. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DatabaseMetadata&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseMetadata> databaseMetadataV2WithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = databaseMetadataV2RequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("databaseMetadataV2", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DatabaseMetadata>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DatabaseMetadata responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DatabaseMetadata>() {});
        

        return new ApiResponse<DatabaseMetadata>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder databaseMetadataV2RequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling databaseMetadataV2");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/database/metadata";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Redirect to a time-limited download URL for one database
   * Answers &#x60;302&#x60;; the bytes come straight from object storage rather than through this API. Follow the redirect. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @throws ApiException if fails to make API call
   */
  public void downloadDatabaseV2(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    downloadDatabaseV2(id, format, null);
  }

  /**
   * Redirect to a time-limited download URL for one database
   * Answers &#x60;302&#x60;; the bytes come straight from object storage rather than through this API. Follow the redirect. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void downloadDatabaseV2(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    downloadDatabaseV2WithHttpInfo(id, format, headers);
  }

  /**
   * Redirect to a time-limited download URL for one database
   * Answers &#x60;302&#x60;; the bytes come straight from object storage rather than through this API. Follow the redirect. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> downloadDatabaseV2WithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format) throws ApiException {
    return downloadDatabaseV2WithHttpInfo(id, format, null);
  }

  /**
   * Redirect to a time-limited download URL for one database
   * Answers &#x60;302&#x60;; the bytes come straight from object storage rather than through this API. Follow the redirect. 
   * @param id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
   * @param format Database file format. (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> downloadDatabaseV2WithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = downloadDatabaseV2RequestBuilder(id, format, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("downloadDatabaseV2", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder downloadDatabaseV2RequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String format, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling downloadDatabaseV2");
    }
    // verify the required parameter 'format' is set
    if (format == null) {
      throw new ApiException(400, "Missing the required parameter 'format' when calling downloadDatabaseV2");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/database/download";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));
    localVarQueryParameterBaseName = "format";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("format", format));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Every database your organization may see, and where each one stands
   * The whole published catalog, with your organization&#39;s licence beside each entry, so &#x60;standing&#x60; says whether a database is yours today (&#x60;licensed&#x60;), was (&#x60;expired&#x60;), or has never been bought (&#x60;unlicensed&#x60;).  Databases commissioned for a single customer are not listed to anyone else. 
   * @return DatabaseList
   * @throws ApiException if fails to make API call
   */
  public DatabaseList listDatabases() throws ApiException {
    return listDatabases(null);
  }

  /**
   * Every database your organization may see, and where each one stands
   * The whole published catalog, with your organization&#39;s licence beside each entry, so &#x60;standing&#x60; says whether a database is yours today (&#x60;licensed&#x60;), was (&#x60;expired&#x60;), or has never been bought (&#x60;unlicensed&#x60;).  Databases commissioned for a single customer are not listed to anyone else. 
   * @param headers Optional headers to include in the request
   * @return DatabaseList
   * @throws ApiException if fails to make API call
   */
  public DatabaseList listDatabases(Map<String, String> headers) throws ApiException {
    ApiResponse<DatabaseList> localVarResponse = listDatabasesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * Every database your organization may see, and where each one stands
   * The whole published catalog, with your organization&#39;s licence beside each entry, so &#x60;standing&#x60; says whether a database is yours today (&#x60;licensed&#x60;), was (&#x60;expired&#x60;), or has never been bought (&#x60;unlicensed&#x60;).  Databases commissioned for a single customer are not listed to anyone else. 
   * @return ApiResponse&lt;DatabaseList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseList> listDatabasesWithHttpInfo() throws ApiException {
    return listDatabasesWithHttpInfo(null);
  }

  /**
   * Every database your organization may see, and where each one stands
   * The whole published catalog, with your organization&#39;s licence beside each entry, so &#x60;standing&#x60; says whether a database is yours today (&#x60;licensed&#x60;), was (&#x60;expired&#x60;), or has never been bought (&#x60;unlicensed&#x60;).  Databases commissioned for a single customer are not listed to anyone else. 
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DatabaseList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DatabaseList> listDatabasesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDatabasesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDatabases", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DatabaseList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DatabaseList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DatabaseList>() {});
        

        return new ApiResponse<DatabaseList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDatabasesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/database/list";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * Refusals are listed too: a denial is what answers \&quot;it stopped working\&quot;, and its absence answers nothing. 
   * @param limit How many attempts to return. Clamped to 200. (optional, default to 50)
   * @return DownloadList
   * @throws ApiException if fails to make API call
   */
  public DownloadList listDownloads(@javax.annotation.Nullable Integer limit) throws ApiException {
    return listDownloads(limit, null);
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * Refusals are listed too: a denial is what answers \&quot;it stopped working\&quot;, and its absence answers nothing. 
   * @param limit How many attempts to return. Clamped to 200. (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return DownloadList
   * @throws ApiException if fails to make API call
   */
  public DownloadList listDownloads(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<DownloadList> localVarResponse = listDownloadsWithHttpInfo(limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * Refusals are listed too: a denial is what answers \&quot;it stopped working\&quot;, and its absence answers nothing. 
   * @param limit How many attempts to return. Clamped to 200. (optional, default to 50)
   * @return ApiResponse&lt;DownloadList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DownloadList> listDownloadsWithHttpInfo(@javax.annotation.Nullable Integer limit) throws ApiException {
    return listDownloadsWithHttpInfo(limit, null);
  }

  /**
   * Your organization&#39;s recent download attempts, newest first
   * Refusals are listed too: a denial is what answers \&quot;it stopped working\&quot;, and its absence answers nothing. 
   * @param limit How many attempts to return. Clamped to 200. (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DownloadList&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DownloadList> listDownloadsWithHttpInfo(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDownloadsRequestBuilder(limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDownloads", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DownloadList>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DownloadList responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DownloadList>() {});
        

        return new ApiResponse<DownloadList>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDownloadsRequestBuilder(@javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/database/downloads";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
